### PR TITLE
Updated for changes to facebook, fb no longer uses sd_src and hd_src.…

### PR DESCRIPTION
**Pull request by guru-florida**
From what I can tell Facebook no longer uses sd_src and hd_src for video urls. I had to switch to parsing <meta property value> tags. This increased code complexity so I also refactored the code to be a class. The videos I needed were private so I added support for private videos by storing facebook auth cookies in a user file (either "cookies" in the current path, or "~/.facebook-cookies" in user home folder). 

Also I had many videos to download so I added parsing of "videos_by" Urls, and will try to download ever video. Unfortunately, facebook only returns the most recent 20. Facebook does a XHR (Ajax) request for next 20 as user scrolls and I didnt go that far.

Take a look and integrate and/or change as you like. :)

### CODE REVIEW

**Comment by sdushantha** [comment]
Thanks for the PR! I'll take a look at it after I read a little about annotations because I've never used them before.

**Comment by sdushantha** [comment]
@guru-florida 
> From what I can tell Facebook no longer uses sd_src and hd_src for video urls.

I just tried running `facebook-dl.py` and it works perfectly....not sure if any changes are needed

**Comment by guru-florida** [comment]
I wonder if it is because I was downloading video a friend posted to a
private group? Can you give that a try?

*Colin MacKenzie*

*FlyingEinstein.com <http://flyingeinstein.com/>*

**Comment by sdushantha** [comment]
@guru-florida

> I wonder if it is because I was downloading video a friend posted to a
private group? Can you give that a try?

That could be the reason. I unfortunetaly can not try it out because I dont have Facebook. I also do not plan on adding more feature to this script because I just wanted to create a simple facebook downloader while doing some code golfing.
If you want to download private facebook videos that try using `youtube-dl` because that tool is able to download from almost any website.

**Comment by guru-florida** [comment]
yup, that is ok. My fork is public too so people can try mine if they run into the same issue as me. I tried youtube_dl first, I use it all the time, but it didnt work for facebook for me either.

**Pull request closed without merging**
